<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Obtener IDs de categorías
        $hamburguesas = DB::table('categorias')->where('nombre', 'Hamburguesas')->first()->id;
        $pizzas = DB::table('categorias')->where('nombre', 'Pizzas')->first()->id;
        $bebidas = DB::table('categorias')->where('nombre', 'Bebidas')->first()->id;
        $postres = DB::table('categorias')->where('nombre', 'Postres')->first()->id;

        $productos = [
            // HAMBURGUESAS (6 productos)
            [
                'nombre' => 'Hamburguesa Clásica',
                'descripcion' => 'Carne jugosa, lechuga, tomate, cebolla y nuestra salsa especial en pan artesanal',
                'precio' => 12.99,
                'precio_descuento' => null,
                'stock' => 25,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesa Premium',
                'descripcion' => 'Doble carne 100% premium, queso cheddar, bacon ahumado, lechuga y tomate en pan artesanal',
                'precio' => 18.99,
                'precio_descuento' => 15.99,
                'stock' => 15,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesa BBQ',
                'descripcion' => 'Carne a la parrilla con salsa BBQ, cebolla caramelizada y queso cheddar',
                'precio' => 14.50,
                'precio_descuento' => null,
                'stock' => 20,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesa Vegana',
                'descripcion' => 'Medallón de quinoa y vegetales, aguacate, lechuga y tomate en pan integral',
                'precio' => 13.99,
                'precio_descuento' => null,
                'stock' => 12,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesa Doble',
                'descripcion' => 'Doble carne, doble queso, bacon, lechuga y tomate para los más hambrientos',
                'precio' => 16.99,
                'precio_descuento' => null,
                'stock' => 8,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesa Crispy',
                'descripcion' => 'Pollo crispy, lechuga, tomate y salsa ranch en pan tostado',
                'precio' => 13.50,
                'precio_descuento' => null,
                'stock' => 3,
                'estado' => 'stock_bajo',
                'activo' => true,
                'categoria_id' => $hamburguesas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PIZZAS (6 productos)
            [
                'nombre' => 'Pizza Margherita',
                'descripcion' => 'Pizza tradicional italiana con salsa de tomate fresca, mozzarella y albahaca sobre masa artesanal',
                'precio' => 18.50,
                'precio_descuento' => null,
                'stock' => 3,
                'estado' => 'stock_bajo',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizza Pepperoni',
                'descripcion' => 'Pizza clásica con abundante pepperoni y queso mozzarella derretido',
                'precio' => 19.99,
                'precio_descuento' => null,
                'stock' => 18,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizza Hawaiana',
                'descripcion' => 'Pizza con jamón, piña y queso mozzarella para los amantes de lo tropical',
                'precio' => 20.50,
                'precio_descuento' => null,
                'stock' => 14,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizza Vegetariana',
                'descripcion' => 'Pizza con pimientos, champiñones, cebolla, tomate y aceitunas',
                'precio' => 18.99,
                'precio_descuento' => null,
                'stock' => 16,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizza Cuatro Quesos',
                'descripcion' => 'Exquisita combinación de mozzarella, parmesano, gorgonzola y ricotta',
                'precio' => 21.99,
                'precio_descuento' => null,
                'stock' => 12,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizza BBQ',
                'descripcion' => 'Pizza con pollo BBQ, cebolla morada, pimientos y salsa barbacoa',
                'precio' => 22.50,
                'precio_descuento' => null,
                'stock' => 0,
                'estado' => 'agotado',
                'activo' => true,
                'categoria_id' => $pizzas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BEBIDAS (6 productos)
            [
                'nombre' => 'Refresco Cola',
                'descripcion' => 'Bebida gaseosa cola refrescante de 500ml',
                'precio' => 3.50,
                'precio_descuento' => null,
                'stock' => 0,
                'estado' => 'agotado',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Smoothie Tropical',
                'descripcion' => 'Refrescante mezcla de frutas tropicales: mango, piña y maracuyá con yogurt natural',
                'precio' => 10.99,
                'precio_descuento' => 8.99,
                'stock' => 25,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Jugo de Naranja Natural',
                'descripcion' => 'Jugo de naranja recién exprimido, 100% natural sin azúcar añadida',
                'precio' => 4.50,
                'precio_descuento' => null,
                'stock' => 30,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Agua Mineral',
                'descripcion' => 'Agua mineral natural de 500ml, perfecta para hidratarte',
                'precio' => 2.50,
                'precio_descuento' => null,
                'stock' => 50,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Café Americano',
                'descripcion' => 'Café americano recién preparado con granos seleccionados',
                'precio' => 3.99,
                'precio_descuento' => null,
                'stock' => 40,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Milkshake Chocolate',
                'descripcion' => 'Cremoso batido de chocolate con helado de vainilla y crema batida',
                'precio' => 6.99,
                'precio_descuento' => null,
                'stock' => 2,
                'estado' => 'stock_bajo',
                'activo' => true,
                'categoria_id' => $bebidas,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // POSTRES (6 productos)
            [
                'nombre' => 'Cheesecake de Frutos Rojos',
                'descripcion' => 'Delicioso cheesecake cremoso con cobertura de frutos rojos frescos',
                'precio' => 7.99,
                'precio_descuento' => null,
                'stock' => 15,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Brownie de Chocolate',
                'descripcion' => 'Brownie casero de chocolate intenso servido caliente con helado de vainilla',
                'precio' => 5.50,
                'precio_descuento' => null,
                'stock' => 20,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Helado de Vainilla',
                'descripcion' => 'Tres bolas de helado cremoso de vainilla natural con cobertura a elección',
                'precio' => 4.99,
                'precio_descuento' => null,
                'stock' => 35,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Tiramisú',
                'descripcion' => 'Clásico postre italiano con café, mascarpone y cacao en polvo',
                'precio' => 8.50,
                'precio_descuento' => null,
                'stock' => 10,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Flan Casero',
                'descripcion' => 'Flan tradicional casero con caramelo líquido y crema batida',
                'precio' => 5.99,
                'precio_descuento' => null,
                'stock' => 18,
                'estado' => 'disponible',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mousse de Chocolate',
                'descripcion' => 'Suave mousse de chocolate belga decorado con virutas de chocolate',
                'precio' => 6.50,
                'precio_descuento' => null,
                'stock' => 4,
                'estado' => 'stock_bajo',
                'activo' => true,
                'categoria_id' => $postres,
                'destacado' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($productos as $producto) {
            DB::table('productos')->updateOrInsert(
                ['nombre' => $producto['nombre']], // Condición para evitar duplicados
                $producto // Datos a insertar/actualizar
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $productosNombres = [
            'Hamburguesa Clásica', 'Hamburguesa Premium', 'Hamburguesa BBQ',
            'Hamburguesa Vegana', 'Hamburguesa Doble', 'Hamburguesa Crispy',
            'Pizza Margherita', 'Pizza Pepperoni', 'Pizza Hawaiana',
            'Pizza Vegetariana', 'Pizza Cuatro Quesos', 'Pizza BBQ',
            'Refresco Cola', 'Smoothie Tropical', 'Jugo de Naranja Natural',
            'Agua Mineral', 'Café Americano', 'Milkshake Chocolate',
            'Cheesecake de Frutos Rojos', 'Brownie de Chocolate', 'Helado de Vainilla',
            'Tiramisú', 'Flan Casero', 'Mousse de Chocolate'
        ];

        DB::table('productos')->whereIn('nombre', $productosNombres)->delete();
    }
};
